import { Metadata } from 'next';
import { supabase } from '@/lib/supabase';
import { AuditReport } from '@/lib/audit-engine/types';
import { CheckCircle2, TrendingDown, ShieldCheck, Zap, BarChart2 } from 'lucide-react';
import Link from 'next/link';

interface SharePageProps {
  params: { id: string };
}

export async function generateMetadata({ params }: SharePageProps): Promise<Metadata> {
  const { id } = await params;
  const { data: audit } = await supabase
    .from('audits')
    .select('report_data')
    .eq('id', id)
    .single();

  const report = audit?.report_data as AuditReport;
  const savings = report?.totalMonthlyDelta ? `$${(report.totalMonthlyDelta * 12).toLocaleString()}` : '$0';

  return {
    title: `Credex AI Audit | Potential Savings: ${savings}/year`,
    description: `I just audited my AI stack with Credex and identified ${savings} in annual savings. Check out my strategic report.`,
    openGraph: {
      title: `AI Stack Audit Result: ${savings} Saved`,
      description: 'Strategic AI SaaS optimization report generated by Credex Intelligence.',
      images: ['/og-image.png'], // Placeholder for Feature 6 OG generation
    },
    twitter: {
      card: 'summary_large_image',
      title: `Credex AI Audit: ${savings}/year reclaimed`,
      description: 'Tactical AI SaaS optimization for modern enterprises.',
    }
  };
}

export default async function SharedAuditPage({ params }: SharePageProps) {
  const { id } = await params;
  const { data: audit, error } = await supabase
    .from('audits')
    .select('*')
    .eq('id', id)
    .single();

  if (error || !audit) {
    return (
      <div className="min-h-screen bg-black flex flex-col items-center justify-center text-center p-6">
        <h1 className="text-3xl font-bold text-white mb-4">Audit Not Found</h1>
        <p className="text-white/40 mb-8">The requested report ID does not exist or has expired.</p>
        <Link href="/" className="px-6 py-3 bg-white text-black rounded-xl font-bold">Run New Audit</Link>
      </div>
    );
  }

  const report = audit.report_data as AuditReport;

  return (
    <div className="min-h-screen bg-[#020617] text-white p-6 md:p-12">
      <div className="max-w-6xl mx-auto">
        <header className="flex items-center justify-between mb-16">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-white rounded-lg flex items-center justify-center">
              <span className="text-black font-black text-xl">C</span>
            </div>
            <span className="font-bold tracking-tighter text-xl">CREDEX AUDIT</span>
          </div>
          <div className="text-[10px] font-bold uppercase tracking-[0.2em] text-white/40">
            Public Report • Read Only
          </div>
        </header>

        <div className="space-y-12">
          {/* Header Stats */}
          <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div className="glass-card p-8 rounded-3xl border-white/5">
              <p className="text-[10px] font-bold uppercase tracking-widest text-white/30 mb-2">Annual Savings Potential</p>
              <h2 className="text-5xl font-bold tracking-tighter text-emerald-400">
                ${(report.totalMonthlyDelta * 12).toLocaleString()}
              </h2>
            </div>
            <div className="glass-card p-8 rounded-3xl border-white/5">
              <p className="text-[10px] font-bold uppercase tracking-widest text-white/30 mb-2">Optimization Strategy</p>
              <h2 className="text-3xl font-bold tracking-tight text-white capitalize">
                Cost-Efficiency
              </h2>
            </div>
            <div className="glass-card p-8 rounded-3xl border-white/5 bg-blue-600/10 border-blue-500/20">
              <p className="text-[10px] font-bold uppercase tracking-widest text-blue-500 mb-2">Strategic Health</p>
              <h2 className="text-3xl font-bold tracking-tight text-white">
                {report.isHealthyStack ? 'Optimized' : 'Action Required'}
              </h2>
            </div>
          </section>

          {/* Recommendations List */}
          <section className="space-y-6">
            <h3 className="text-lg font-semibold tracking-tight flex items-center gap-3">
              <BarChart2 className="w-4 h-4 text-blue-500" />
              Strategic Recommendations
            </h3>
            <div className="grid grid-cols-1 gap-4">
              {report.recommendations.map((rec) => (
                <div key={rec.id} className="glass-card p-6 rounded-2xl border-white/5 flex flex-col md:flex-row md:items-center justify-between gap-6">
                  <div>
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-[10px] font-bold uppercase tracking-widest text-blue-500 bg-blue-500/10 px-2 py-0.5 rounded">
                        {rec.recommendationType}
                      </span>
                      <h4 className="font-semibold text-white">{rec.title}</h4>
                    </div>
                    <p className="text-sm text-white/40 max-w-xl">{rec.explanation.summary}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs font-bold uppercase tracking-widest text-emerald-400 mb-1">Impact</p>
                    <p className="text-2xl font-bold text-white">-${rec.monthlyDelta.toLocaleString()}/mo</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Viral Call to Action */}
          <section className="pt-24 pb-12 text-center border-t border-white/5">
            <h3 className="text-3xl font-bold mb-6">Want to audit your own AI stack?</h3>
            <p className="text-white/40 mb-12 max-w-xl mx-auto">Credex identifies hidden costs and security risks in your AI tools in under 60 seconds.</p>
            <Link href="/" className="px-10 py-5 bg-white text-black rounded-2xl font-bold hover:scale-105 transition-transform inline-block shadow-2xl shadow-white/10">
              Run Your Free AI Audit
            </Link>
          </section>
        </div>
      </div>
    </div>
  );
}
